export const credentialRegistryAbi = [
  {
    type: "function",
    name: "registerApp",
    inputs: [{ name: "recoveryTimelock_", type: "uint256" }],
    outputs: [{ name: "appId_", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "suspendApp",
    inputs: [{ name: "appId_", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "activateApp",
    inputs: [{ name: "appId_", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setAppRecoveryTimelock",
    inputs: [
      { name: "appId_", type: "uint256" },
      { name: "recoveryTimelock_", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferAppAdmin",
    inputs: [
      { name: "appId_", type: "uint256" },
      { name: "newAdmin_", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acceptAppAdmin",
    inputs: [{ name: "appId_", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pendingAppAdmin",
    inputs: [{ name: "appId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setAppScorer",
    inputs: [
      { name: "appId_", type: "uint256" },
      { name: "scorer_", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "apps",
    inputs: [{ name: "appId", type: "uint256" }],
    outputs: [
      { name: "status", type: "uint8" },
      { name: "recoveryTimelock", type: "uint256" },
      { name: "admin", type: "address" },
      { name: "scorer", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "appIsActive",
    inputs: [{ name: "appId_", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "defaultScorer",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "appMerkleTreeDuration",
    inputs: [{ name: "appId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "defaultMerkleTreeDuration",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setAppMerkleTreeDuration",
    inputs: [
      { name: "appId_", type: "uint256" },
      { name: "merkleTreeDuration_", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAppSemaphoreGroupIds",
    inputs: [{ name: "appId_", type: "uint256" }],
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "credentialGroups",
    inputs: [{ name: "credentialGroupId", type: "uint256" }],
    outputs: [
      { name: "status", type: "uint8" },
      { name: "validityDuration", type: "uint256" },
      { name: "familyId", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCredentialGroupIds",
    inputs: [],
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AppRegistered",
    inputs: [
      { name: "appId", type: "uint256", indexed: true },
      { name: "admin", type: "address", indexed: true },
      { name: "recoveryTimelock", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "AppAdminTransferred",
    inputs: [
      { name: "appId", type: "uint256", indexed: true },
      { name: "oldAdmin", type: "address", indexed: true },
      { name: "newAdmin", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "AppAdminTransferInitiated",
    inputs: [
      { name: "appId", type: "uint256", indexed: true },
      { name: "currentAdmin", type: "address", indexed: true },
      { name: "newAdmin", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "AppStatusChanged",
    inputs: [
      { name: "appId", type: "uint256", indexed: true },
      { name: "status", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "AppMerkleTreeDurationSet",
    inputs: [
      { name: "appId", type: "uint256", indexed: true },
      { name: "merkleTreeDuration", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "AppScorerSet",
    inputs: [
      { name: "appId", type: "uint256", indexed: true },
      { name: "scorer", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "AppRecoveryTimelockSet",
    inputs: [
      { name: "appId", type: "uint256", indexed: true },
      { name: "timelock", type: "uint256", indexed: false },
    ],
  },
  {
    type: "error",
    name: "NotAppAdmin",
    inputs: [],
  },
  {
    type: "error",
    name: "AppNotActive",
    inputs: [],
  },
  {
    type: "error",
    name: "AppNotSuspended",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidAdminAddress",
    inputs: [],
  },
  {
    type: "error",
    name: "NotPendingAdmin",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidScorerContract",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidScorerAddress",
    inputs: [],
  },
] as const;
